const actionTypes = {
  CART_ITEM_GET: 'CART_ITEM_GET',
  CART_ITEM_SET_SUCCESS: 'CART_ITEM_SET_SUCCESS',
  CART_ITEM_UPDATE: 'CART_ITEM_UPDATE',
  CART_RESET: 'CART_RESET',
  CART_QTY_CHANGE_HANDLER: 'CART_QTY_CHANGE_HANDLER',
}

export default actionTypes
